<?php session_start(); ?>
<?php include "../menu.php"; ?>
<?php
system("mkdir ../problems/" . $_POST['title']);
$file = fopen("../problems/" . $_POST['title'] . "/index.md", "w");
fwrite($file, $_POST['t']);
file_put_contents("../problems/problems.txt", $_POST['title'] . "\n", FILE_APPEND);
file_put_contents("../problems/" . $_POST['title'] . "/index.php", '<?php session_start();?><!DOCTYPE html><html><head><title>'.$_POST["title"].'</title><?php include "../../menu.php"; ?><link rel="stylesheet" href="https://use.sevencdn.com/npm/katex@0.16.11/dist/katex.min.css"></head><body><div style = "padding:2%; margin:2%; color:black; text-align:center;"><h1>'.$_POST["title"].'</h1></div><div class = "layui-panel" style = "padding:1%; margin:1%;">题目描述</div><div class = "layui-panel markdown-body" style = "padding:2%; margin:2%;">'.$_POST["h"].'</div><script src = "https://cdn.jsdelivr.net/gh/laiyiwen-02/cdn@0.0.1/prism/prism.js"></script><script>const codeElements = document.querySelectorAll("code");codeElements.forEach(element => {element.className = "language-text"});</script><script src="https://use.sevencdn.com/npm/katex@0.16.11/dist/katex.min.js"></script><script src="https://use.sevencdn.com/npm/katex@0.16.11/dist/contrib/auto-render.min.js" onload = '."'renderMathInElement(document.body, {delimiters: [{left: ".'"$$"'.", right: ".'"$$"'.", display: true}, {left: ".'"$"'.", right: ".'"$"'.", display: false} ], macros: {".'"\\\\geq"'.": ".'"\\\\geqslant"'.", ".'"\\\\leq"'.": ".'"\\\\leqslant"'." } }); '></script><script src = 'https://s4.zstatic.net/ajax/libs/layui/2.11.1/layui.js'></script>"."</body></html>");
fclose($file);
echo "<script>alert('提交成功');</script>";
echo "<script>window.location.href = '/problems/';</script>";
?>
<?php include "../footer.php"; ?>

'<?php session_start();?><!DOCTYPE html><html><head><title>'.$_POST["title"].'</title><?php include "../../menu.php"; ?><link rel="stylesheet" href="https://use.sevencdn.com/npm/katex@0.16.11/dist/katex.min.css"></head><body><div class = "layui-panel" style = "padding:2%; margin:2%; color:black;"><h1>'.$_POST["title"].'</h1></div><div class = "layui-panel markdown-body" style = "padding:2%; margin:2%;">'.$_POST["h"].'</div><script src = "https://cdn.jsdelivr.net/gh/laiyiwen-02/cdn@0.0.1/prism/prism.js"></script><script>const codeElements = document.querySelectorAll("code");codeElements.forEach(element => {element.className = "language-text"});</script><script src="https://use.sevencdn.com/npm/katex@0.16.11/dist/katex.min.js"></script><script src="https://use.sevencdn.com/npm/katex@0.16.11/dist/contrib/auto-render.min.js" onload = '."'renderMathInElement(document.body, {delimiters: [{left: ".'"$$"'.", right: ".'"$$"'.", display: true}, {left: ".'"$"'.", right: ".'"$"'.", display: false} ], macros: {".'"\\\\geq"'.": ".'"\\\\geqslant"'.", ".'"\\\\leq"'.": ".'"\\\\leqslant"'." } }); '></script><script src = 'https://s4.zstatic.net/ajax/libs/layui/2.11.1/layui.js'></script>".'<div class = "layui-panel" style = "padding: 2%; margin: 2%;"><script src="https://giscus.app/client.js" data-repo="Laiyiwen-02/giscus" data-repo-id="R_kgDOMhxnTw" data-category="Announcements" data-category-id="DIC_kwDOMhxnT84ChhxH" data-mapping="url" data-strict="0" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="bottom" data-theme="preferred_color_scheme" data-lang="zh-CN" crossorigin="anonymous" async></script></div>'."</body></html>"